version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
  app:
    build:
      args:
        - APP_ENV=dev
      context: ./
      dockerfile: PHP.Dockerfile
    restart: always
    volumes:
      - ./app:/var/www/html
  db:
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
  adminer: 
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db


volumes:
  mysqldata: {}